Fix #16 along with other formatting
tessel/servo-pca9685 pull request #18
Opened 2017-07-03 10:56 UTC by brihijoshi

Added Code of Conduct, along with removing spaces to produce proper Markdown titles. Also, removed the # for * in bullet points.

2017-07-03 15:24 UTC, HipsterBrown approved these changes

2017-07-03 22:07 UTC, Frijol requested changes

2017-07-03 22:07 UTC, Frijol commented on README.md
> -&#x20;<a href="#api-servo-configure-whichServo-minPWM-maxPWM-callback-Sets-the-PWM-max-and-min-for-the-specified-servo" name="api-servo-configure-whichServo-minPWM-maxPWM-callback-Sets-the-PWM-max-an
Please leave these! See note in RFID repo.

2017-07-03 22:08 UTC, Frijol commented
fixes https://github.com/tessel/servo-pca9685/issues/16

2017-07-04 00:34 UTC, brihijoshi commented on README.md
> -&#x20;<a href="#api-servo-configure-whichServo-minPWM-maxPWM-callback-Sets-the-PWM-max-and-min-for-the-specified-servo" name="api-servo-configure-whichServo-minPWM-maxPWM-callback-Sets-the-PWM-max-an
Seen. Apologies. Fixing ASAP

2017-07-04 18:17 UTC, Frijol approved these changes

2017-07-04 18:17 UTC, merged